<?php

declare(strict_types=1);

namespace Devlop\Colours\Enums;

use LogicException;

abstract class CssColors
{
    public const ALICEBLUE = '#f0f8ff';
    public const ANTIQUEWHITE = '#faebd7';
    public const AQUA = '#00ffff';
    public const AQUAMARINE = '#7fffd4';
    public const AZURE = '#f0ffff';
    public const BEIGE = '#f5f5dc';
    public const BISQUE = '#ffe4c4';
    public const BLACK = '#000000';
    public const BLANCHEDALMOND = '#ffebcd';
    public const BLUE = '#0000ff';
    public const BLUEVIOLET = '#8a2be2';
    public const BROWN = '#a52a2a';
    public const BURLYWOOD = '#deb887';
    public const CADETBLUE = '#5f9ea0';
    public const CHARTREUSE = '#7fff00';
    public const CHOCOLATE = '#d2691e';
    public const CORAL = '#ff7f50';
    public const CORNFLOWERBLUE = '#6495ed';
    public const CORNSILK = '#fff8dc';
    public const CRIMSON = '#dc143c';
    public const CYAN = self::AQUA;
    public const DARKBLUE = '#00008b';
    public const DARKCYAN = '#008b8b';
    public const DARKGOLDENROD = '#b8860b';
    public const DARKGRAY = '#a9a9a9';
    public const DARKGREEN = '#006400';
    public const DARKGREY = self::DARKGRAY;
    public const DARKKHAKI = '#bdb76b';
    public const DARKMAGENTA = '#8b008b';
    public const DARKOLIVEGREEN = '#556b2f';
    public const DARKORANGE = '#ff8c00';
    public const DARKORCHID = '#9932cc';
    public const DARKRED = '#8b0000';
    public const DARKSALMON = '#e9967a';
    public const DARKSEAGREEN = '#8fbc8f';
    public const DARKSLATEBLUE = '#483d8b';
    public const DARKSLATEGRAY = '#2f4f4f';
    public const DARKSLATEGREY = self::DARKSLATEGRAY;
    public const DARKTURQUOISE = '#00ced1';
    public const DARKVIOLET = '#9400d3';
    public const DEEPPINK = '#ff1493';
    public const DEEPSKYBLUE = '#00bfff';
    public const DIMGRAY = '#696969';
    public const DIMGREY = self::DIMGRAY;
    public const DODGERBLUE = '#1e90ff';
    public const FIREBRICK = '#b22222';
    public const FLORALWHITE = '#fffaf0';
    public const FORESTGREEN = '#228b22';
    public const FUCHSIA = '#ff00ff';
    public const GAINSBORO = '#dcdcdc';
    public const GHOSTWHITE = '#f8f8ff';
    public const GOLD = '#ffd700';
    public const GOLDENROD = '#daa520';
    public const GRAY = '#808080';
    public const GREEN = '#008000';
    public const GREENYELLOW = '#adff2f';
    public const GREY = self::GRAY;
    public const HONEYDEW = '#f0fff0';
    public const HOTPINK = '#ff69b4';
    public const INDIANRED = '#cd5c5c';
    public const INDIGO = '#4b0082';
    public const IVORY = '#fffff0';
    public const KHAKI = '#f0e68c';
    public const LAVENDER = '#e6e6fa';
    public const LAVENDERBLUSH = '#fff0f5';
    public const LAWNGREEN = '#7cfc00';
    public const LEMONCHIFFON = '#fffacd';
    public const LIGHTBLUE = '#add8e6';
    public const LIGHTCORAL = '#f08080';
    public const LIGHTCYAN = '#e0ffff';
    public const LIGHTGOLDENRODYELLOW = '#fafad2';
    public const LIGHTGRAY = '#d3d3d3';
    public const LIGHTGREEN = '#90ee90';
    public const LIGHTGREY = self::LIGHTGRAY;
    public const LIGHTPINK = '#ffb6c1';
    public const LIGHTSALMON = '#ffa07a';
    public const LIGHTSEAGREEN = '#20b2aa';
    public const LIGHTSKYBLUE = '#87cefa';
    public const LIGHTSLATEGRAY = '#778899';
    public const LIGHTSLATEGREY = self::LIGHTSLATEGRAY;
    public const LIGHTSTEELBLUE = '#b0c4de';
    public const LIGHTYELLOW = '#ffffe0';
    public const LIME = '#00ff00';
    public const LIMEGREEN = '#32cd32';
    public const LINEN = '#faf0e6';
    public const MAGENTA = self::FUCHSIA;
    public const MAROON = '#800000';
    public const MEDIUMAQUAMARINE = '#66cdaa';
    public const MEDIUMBLUE = '#0000cd';
    public const MEDIUMORCHID = '#ba55d3';
    public const MEDIUMPURPLE = '#9370db';
    public const MEDIUMSEAGREEN = '#3cb371';
    public const MEDIUMSLATEBLUE = '#7b68ee';
    public const MEDIUMSPRINGGREEN = '#00fa9a';
    public const MEDIUMTURQUOISE = '#48d1cc';
    public const MEDIUMVIOLETRED = '#c71585';
    public const MIDNIGHTBLUE = '#191970';
    public const MINTCREAM = '#f5fffa';
    public const MISTYROSE = '#ffe4e1';
    public const MOCCASIN = '#ffe4b5';
    public const NAVAJOWHITE = '#ffdead';
    public const NAVY = '#000080';
    public const OLDLACE = '#fdf5e6';
    public const OLIVE = '#808000';
    public const OLIVEDRAB = '#6b8e23';
    public const ORANGE = '#ffa500';
    public const ORANGERED = '#ff4500';
    public const ORCHID = '#da70d6';
    public const PALEGOLDENROD = '#eee8aa';
    public const PALEGREEN = '#98fb98';
    public const PALETURQUOISE = '#afeeee';
    public const PALEVIOLETRED = '#db7093';
    public const PAPAYAWHIP = '#ffefd5';
    public const PEACHPUFF = '#ffdab9';
    public const PERU = '#cd853f';
    public const PINK = '#ffc0cb';
    public const PLUM = '#dda0dd';
    public const POWDERBLUE = '#b0e0e6';
    public const PURPLE = '#800080';
    public const REBECCAPURPLE = '#663399';
    public const RED = '#ff0000';
    public const ROSYBROWN = '#bc8f8f';
    public const ROYALBLUE = '#4169e1';
    public const SADDLEBROWN = '#8b4513';
    public const SALMON = '#fa8072';
    public const SANDYBROWN = '#f4a460';
    public const SEAGREEN = '#2e8b57';
    public const SEASHELL = '#fff5ee';
    public const SIENNA = '#a0522d';
    public const SILVER = '#c0c0c0';
    public const SKYBLUE = '#87ceeb';
    public const SLATEBLUE = '#6a5acd';
    public const SLATEGRAY = '#708090';
    public const SLATEGREY = self::SLATEGRAY;
    public const SNOW = '#fffafa';
    public const SPRINGGREEN = '#00ff7f';
    public const STEELBLUE = '#4682b4';
    public const TAN = '#d2b48c';
    public const TEAL = '#008080';
    public const THISTLE = '#d8bfd8';
    public const TOMATO = '#ff6347';
    public const TURQUOISE = '#40e0d0';
    public const VIOLET = '#ee82ee';
    public const WHEAT = '#f5deb3';
    public const WHITE = '#ffffff';
    public const WHITESMOKE = '#f5f5f5';
    public const YELLOW = '#ffff00';
    public const YELLOWGREEN = '#9acd32';

    /** @readonly */
    public $colors = [
        'aliceblue' => self::ALICEBLUE,
        'antiquewhite' => self::ANTIQUEWHITE,
        'aqua' => self::AQUA,
        'aquamarine' => self::AQUAMARINE,
        'azure' => self::AZURE,
        'beige' => self::BEIGE,
        'bisque' => self::BISQUE,
        'black' => self::BLACK,
        'blanchedalmond' => self::BLANCHEDALMOND,
        'blue' => self::BLUE,
        'blueviolet' => self::BLUEVIOLET,
        'brown' => self::BROWN,
        'burlywood' => self::BURLYWOOD,
        'cadetblue' => self::CADETBLUE,
        'chartreuse' => self::CHARTREUSE,
        'chocolate' => self::CHOCOLATE,
        'coral' => self::CORAL,
        'cornflowerblue' => self::CORNFLOWERBLUE,
        'cornsilk' => self::CORNSILK,
        'crimson' => self::CRIMSON,
        'cyan' => self::CYAN,
        'darkblue' => self::DARKBLUE,
        'darkcyan' => self::DARKCYAN,
        'darkgoldenrod' => self::DARKGOLDENROD,
        'darkgray' => self::DARKGRAY,
        'darkgreen' => self::DARKGREEN,
        'darkgrey' => self::DARKGREY,
        'darkkhaki' => self::DARKKHAKI,
        'darkmagenta' => self::DARKMAGENTA,
        'darkolivegreen' => self::DARKOLIVEGREEN,
        'darkorange' => self::DARKORANGE,
        'darkorchid' => self::DARKORCHID,
        'darkred' => self::DARKRED,
        'darksalmon' => self::DARKSALMON,
        'darkseagreen' => self::DARKSEAGREEN,
        'darkslateblue' => self::DARKSLATEBLUE,
        'darkslategray' => self::DARKSLATEGRAY,
        'darkslategrey' => self::DARKSLATEGREY,
        'darkturquoise' => self::DARKTURQUOISE,
        'darkviolet' => self::DARKVIOLET,
        'deeppink' => self::DEEPPINK,
        'deepskyblue' => self::DEEPSKYBLUE,
        'dimgray' => self::DIMGRAY,
        'dimgrey' => self::DIMGREY,
        'dodgerblue' => self::DODGERBLUE,
        'firebrick' => self::FIREBRICK,
        'floralwhite' => self::FLORALWHITE,
        'forestgreen' => self::FORESTGREEN,
        'fuchsia' => self::FUCHSIA,
        'gainsboro' => self::GAINSBORO,
        'ghostwhite' => self::GHOSTWHITE,
        'gold' => self::GOLD,
        'goldenrod' => self::GOLDENROD,
        'gray' => self::GRAY,
        'green' => self::GREEN,
        'greenyellow' => self::GREENYELLOW,
        'grey' => self::GREY,
        'honeydew' => self::HONEYDEW,
        'hotpink' => self::HOTPINK,
        'indianred' => self::INDIANRED,
        'indigo' => self::INDIGO,
        'ivory' => self::IVORY,
        'khaki' => self::KHAKI,
        'lavender' => self::LAVENDER,
        'lavenderblush' => self::LAVENDERBLUSH,
        'lawngreen' => self::LAWNGREEN,
        'lemonchiffon' => self::LEMONCHIFFON,
        'lightblue' => self::LIGHTBLUE,
        'lightcoral' => self::LIGHTCORAL,
        'lightcyan' => self::LIGHTCYAN,
        'lightgoldenrodyellow' => self::LIGHTGOLDENRODYELLOW,
        'lightgray' => self::LIGHTGRAY,
        'lightgreen' => self::LIGHTGREEN,
        'lightgrey' => self::LIGHTGREY,
        'lightpink' => self::LIGHTPINK,
        'lightsalmon' => self::LIGHTSALMON,
        'lightseagreen' => self::LIGHTSEAGREEN,
        'lightskyblue' => self::LIGHTSKYBLUE,
        'lightslategray' => self::LIGHTSLATEGRAY,
        'lightslategrey' => self::LIGHTSLATEGREY,
        'lightsteelblue' => self::LIGHTSTEELBLUE,
        'lightyellow' => self::LIGHTYELLOW,
        'lime' => self::LIME,
        'limegreen' => self::LIMEGREEN,
        'linen' => self::LINEN,
        'magenta' => self::MAGENTA,
        'maroon' => self::MAROON,
        'mediumaquamarine' => self::MEDIUMAQUAMARINE,
        'mediumblue' => self::MEDIUMBLUE,
        'mediumorchid' => self::MEDIUMORCHID,
        'mediumpurple' => self::MEDIUMPURPLE,
        'mediumseagreen' => self::MEDIUMSEAGREEN,
        'mediumslateblue' => self::MEDIUMSLATEBLUE,
        'mediumspringgreen' => self::MEDIUMSPRINGGREEN,
        'mediumturquoise' => self::MEDIUMTURQUOISE,
        'mediumvioletred' => self::MEDIUMVIOLETRED,
        'midnightblue' => self::MIDNIGHTBLUE,
        'mintcream' => self::MINTCREAM,
        'mistyrose' => self::MISTYROSE,
        'moccasin' => self::MOCCASIN,
        'navajowhite' => self::NAVAJOWHITE,
        'navy' => self::NAVY,
        'oldlace' => self::OLDLACE,
        'olive' => self::OLIVE,
        'olivedrab' => self::OLIVEDRAB,
        'orange' => self::ORANGE,
        'orangered' => self::ORANGERED,
        'orchid' => self::ORCHID,
        'palegoldenrod' => self::PALEGOLDENROD,
        'palegreen' => self::PALEGREEN,
        'paleturquoise' => self::PALETURQUOISE,
        'palevioletred' => self::PALEVIOLETRED,
        'papayawhip' => self::PAPAYAWHIP,
        'peachpuff' => self::PEACHPUFF,
        'peru' => self::PERU,
        'pink' => self::PINK,
        'plum' => self::PLUM,
        'powderblue' => self::POWDERBLUE,
        'purple' => self::PURPLE,
        'rebeccapurple' => self::REBECCAPURPLE,
        'red' => self::RED,
        'rosybrown' => self::ROSYBROWN,
        'royalblue' => self::ROYALBLUE,
        'saddlebrown' => self::SADDLEBROWN,
        'salmon' => self::SALMON,
        'sandybrown' => self::SANDYBROWN,
        'seagreen' => self::SEAGREEN,
        'seashell' => self::SEASHELL,
        'sienna' => self::SIENNA,
        'silver' => self::SILVER,
        'skyblue' => self::SKYBLUE,
        'slateblue' => self::SLATEBLUE,
        'slategray' => self::SLATEGRAY,
        'slategrey' => self::SLATEGREY,
        'snow' => self::SNOW,
        'springgreen' => self::SPRINGGREEN,
        'steelblue' => self::STEELBLUE,
        'tan' => self::TAN,
        'teal' => self::TEAL,
        'thistle' => self::THISTLE,
        'tomato' => self::TOMATO,
        'turquoise' => self::TURQUOISE,
        'violet' => self::VIOLET,
        'wheat' => self::WHEAT,
        'white' => self::WHITE,
        'whitesmoke' => self::WHITESMOKE,
        'yellow' => self::YELLOW,
        'yellowgreen' => self::YELLOWGREEN,
    ];

    private function __construct()
    {
        throw new LogicException(__CLASS__ . ' cannot be instantiated.');
    }
}
